{% set name = "bml" %}
{% set version = "2.3.0" %}
{% set build = 0 %}
{% set mpi = mpi or "nompi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lanl/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 45f02101b934b9d01dafeab28ca786cea1b5b4ef3096cf50d73e098916c857b2

{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% endif %}
build:
  number: {{ build }}
  skip: true  # [win or osx]

  script: "bash ${RECIPE_DIR}/build-cf.sh"
  script_env:
    - CMAKE_BUILD_TYPE=Release
    - BUILD_SHARED_LIBS=yes
    - BML_OPENMP=yes
    - BML_MPI=yes  # [mpi != "nompi"]
    - BML_COMPLEX=yes
    - BML_TESTING=yes
    - BLAS_VENDOR=GNU
    - EXTRA_FFLAGS=-ffree-line-length-none

  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  {% if mpi != "nompi" %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - {{ mpi }}  # [mpi != "nompi"]
    - libblas
    - liblapack
  run:
    - {{ mpi }}  # [mpi != "nompi"]

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/include/bml.h
    - test -f $PREFIX/include/bml.mod
    - test -f $PREFIX/lib/libbml${SHLIB_EXT}
    - test -f $PREFIX/lib/libbml_fortran${SHLIB_EXT}

about:
  home: https://lanl.github.io/bml
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
  summary: The Basic Matrix Library (bml)
  description: |
    The basic matrix library (bml) is a collection of various matrix data formats
    (for dense and sparse) and their associated algorithms for basic matrix operations.
    Application programming interfaces (API) are available for both C and Fortran.
    The current status of this library allows us to use two different formats
    for representing matrix data. Currently these formats are dense, ELLPACK-R,
    ELLBLOCK, ELLSORT, and CSR.
  dev_url: https://github.com/lanl/bml

extra:
  recipe-maintainers:
    - awvwgk
    - nicolasbock
